
const KEY='supporthub.v2',DAY=864e5,HR=36e5,ST=['Open','In Progress','Resolved'],PR=['Low','Medium','High'],TY=['Product Query','Complaint','Delivery','Installation','Warranty / Service','Billing','Other'],CATS=['Getting Started','Billing','Troubleshooting','Warranty & Service','Delivery','General'],
LBL=['Very Dissatisfied','Dissatisfied','Neutral','Satisfied','Very Satisfied'],COL=['#ff5e68','#ff9855','#ffc94d','#6bdca8','#15b977'],PAL=['#1769ff','#8b5cf6','#19b977','#f6ae1a','#ff5261','#14b8c4','#94a3b8'],
KW=/urgent|immediate|asap|crash|fraud|refund|not working|failed/i,EM='<div class="empty">No tickets found. Try another search or filter.</div>',
NAV=[['dashboard','home','Dashboard'],['tickets','ticket','Tickets'],['customers','user','Customers'],['analytics','chart','Analytics'],['kb','book','Knowledge Base'],['automation','zap','Automation'],['team','users','Team'],['settings','sliders','Settings']];
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),
ini=n=>String(n).split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase(),avg=a=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0,
fmt=ts=>new Date(ts).toLocaleString('en-IN',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}),fmtD=ts=>new Date(ts).toLocaleDateString('en-US',{month:'short',day:'numeric'}),
ago=ts=>{const m=Math.floor((Date.now()-ts)/6e4);return m<1?'Just now':m<60?m+'m ago':m<1440?Math.floor(m/60)+'h ago':Math.floor(m/1440)+'d ago'},
dur=ms=>{const n=Math.round(ms/6e4),h=Math.floor(n/60),d=Math.floor(h/24);return n<60?n+'m':h<24?h+'h '+n%60+'m':d+'d '+h%24+'h'},
dayS=i=>{const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-i);return d.getTime()},
sc=s=>s=='Resolved'?'resolved':s=='In Progress'?'progress':'open',
st=(t,T)=>t.hist.reduce((a,h)=>h.t<=T?h.s:a,null),snap=(T,f)=>S.tickets.filter(t=>t.created<=T&&f(st(t,T))).length;
const IP={"home": "<path d=\"M3 11l9-8 9 8\"/><path d=\"M5 10v10h14V10\"/><path d=\"M10 20v-6h4v6\"/>", "ticket": "<path d=\"M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z\"/>", "user": "<path d=\"M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2\"/><circle cx=\"12\" cy=\"7\" r=\"4\"/>", "users": "<path d=\"M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2\"/><circle cx=\"9\" cy=\"7\" r=\"4\"/><path d=\"M23 21v-2a4 4 0 0 0-3-3.87\"/><path d=\"M16 3.13a4 4 0 0 1 0 7.75\"/>", "chart": "<path d=\"M18 20V10\"/><path d=\"M12 20V4\"/><path d=\"M6 20v-6\"/>", "book": "<path d=\"M4 19.5A2.5 2.5 0 0 1 6.5 17H20\"/><path d=\"M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2z\"/>", "zap": "<path d=\"M13 2L3 14h9l-1 8 10-12h-9l1-8z\"/>", "sliders": "<path d=\"M4 21v-7M4 10V3M12 21v-9M12 8V3M20 21v-5M20 12V3M1 14h6M9 8h6M17 16h6\"/>", "alert": "<circle cx=\"12\" cy=\"12\" r=\"10\"/><path d=\"M12 8v4M12 16h.01\"/>", "clock": "<circle cx=\"12\" cy=\"12\" r=\"10\"/><path d=\"M12 6v6l4 2\"/>", "check": "<path d=\"M22 11.08V12a10 10 0 1 1-5.93-9.14\"/><path d=\"M22 4L12 14.01l-3-3\"/>", "plus": "<circle cx=\"12\" cy=\"12\" r=\"10\"/><path d=\"M12 8v8M8 12h8\"/>", "refresh": "<path d=\"M23 4v6h-6\"/><path d=\"M1 20v-6h6\"/><path d=\"M3.5 9a9 9 0 0 1 14.85-3.36L23 10M1 14l4.65 4.36A9 9 0 0 0 20.5 15\"/>", "edit": "<path d=\"M12 20h9\"/><path d=\"M16.5 3.5a2.1 2.1 0 0 1 3 3L7 19l-4 1 1-4z\"/>", "trash": "<path d=\"M3 6h18\"/><path d=\"M8 6V4h8v2\"/><path d=\"M19 6l-1 14H6L5 6\"/>", "up": "<path d=\"M12 19V5M5 12l7-7 7 7\"/>", "minus": "<path d=\"M5 12h14\"/>", "down": "<path d=\"M12 5v14M19 12l-7 7-7-7\"/>", "thumb": "<path d=\"M14 9V5a3 3 0 0 0-3-3l-4 9v11h11.3a2 2 0 0 0 2-1.7l1.4-9a2 2 0 0 0-2-2.3zM7 22H4a2 2 0 0 1-2-2v-7a2 2 0 0 1 2-2h3\"/>"},icon=(n,z=18,w=2)=>`<svg width="${z}" height="${z}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="${w}" stroke-linecap="round" stroke-linejoin="round">${IP[n]}</svg>`;
const mkLog=(tk,tm)=>{const l=[];tk.forEach(t=>{l.push({ts:t.created,k:'new',id:t.id,text:t.name+' sent a new ticket',sub:t.type});if(t.resolvedAt){const m=tm.find(x=>x.id==t.assignee);l.push({ts:t.resolvedAt,k:'res',id:t.id,text:(m?m.name:'An agent')+' resolved a ticket',sub:t.type})}});return l.sort((a,b)=>b.ts-a.ts).slice(0,300)};
function seed(){let x=11;const r=()=>(x=x*16807%2147483647)/2147483647,now=Date.now(),
team=[['Aman Khan','Senior Agent'],['Riya Sharma','Support Lead'],['Priya Tiwari','Agent'],['Karan Mehta','Agent']].map((m,i)=>({id:i+1,name:m[0],role:m[1]})),
cu=[['Emily Carter','9876543210'],['James Wilson','9123456780'],['Sophia Lee','9988776655'],['Daniel Kim','9898989898'],['Olivia Martinez','9001122334'],['Liam Brown','9012345678'],['Rahul Kumar','9811122233'],['Neha Gupta','9700011122']],
is=[['Complaint','Cannot access account after password reset.'],['Billing','Billing amount does not match the quotation shared earlier.'],['Product Query','Wants to know if a dark mode option is available.'],['Complaint','Checkout failed on the payment page.'],['Installation','Installation flow crashes after the verification step.'],['Warranty / Service','Unable to reset warranty portal password.'],['Delivery','Order has not arrived on the promised date.'],['Other','Needs an invoice copy for last month.']],tk=[];
for(let i=0;i<32;i++){const c=cu[r()*cu.length|0],q=is[r()*is.length|0],cr=now-r()*14*DAY,sp=now-cr,pr=r(),h=[{s:'Open',t:cr}];let s='Open';
if(r()<Math.min(.92,sp/DAY/9))s='Resolved';else if(r()<.4)s='In Progress';
if(s!='Open'&&(s=='In Progress'||r()<.6))h.push({s:'In Progress',t:cr+sp*(.05+r()*.3)});
if(s=='Resolved')h.push({s:'Resolved',t:cr+sp*(.4+r()*.55)});
const rz=s=='Resolved'?h[h.length-1].t:null,z=r();
tk.push({id:0,name:c[0],phone:c[1],type:q[0],desc:q[1],priority:pr<.25?'High':pr<.65?'Medium':'Low',status:s,created:cr,updated:h[h.length-1].t,hist:h,assignee:team[i%4].id,resolvedAt:rz,rating:rz&&r()<.88?(z<.65?5:z<.88?4:z<.95?3:z<.99?2:1):null,notes:[],kw:1,aa:1})}
tk.sort((a,b)=>a.created-b.created).forEach((t,i)=>t.id=10001+i);
const kb=[['Resetting a customer password','Getting Started','1. Confirm the registered phone number.\n2. Send a reset link from the account page.\n3. Check the customer can log in, then resolve the ticket.'],['Handling billing mismatches','Billing','Compare the invoice with the original quotation, note the difference in the ticket, and escalate to billing if it is more than the agreed tolerance.'],['Payment page errors','Troubleshooting','Ask the customer to clear the browser cache and retry with another payment method. If it still fails, collect a screenshot and the time of failure.'],['Warranty claim process','Warranty & Service','Verify the purchase date and invoice number, check the warranty period, then book a service visit or a replacement request.'],['Delayed delivery checklist','Delivery','Check tracking status, contact the courier, apologise to the customer and add a new delivery date in the ticket notes.'],['Writing a good customer reply','General','Greet by name, repeat the problem in your own words, give the next step with a time, and ask if anything else is needed.']].map((k,i)=>({id:i+1,title:k[0],cat:k[1],body:k[2],views:0,up:0}));
return{tickets:tk,team,kb,log:mkLog(tk,team),rules:{a:1,k:1,e:1,n:{a:0,k:0,e:0}},settings:{name:'Support Admin',role:'Support Team',sla:24,notif:true}}}
function load(){try{const s=JSON.parse(localStorage.getItem(KEY));if(s&&Array.isArray(s.tickets))return s}catch(e){}
try{const o=JSON.parse(localStorage.getItem('ticketTracker.v1'));if(o&&o.length){const s=seed();s.tickets=o.map(t=>({...t,hist:[{s:'Open',t:t.created}].concat(t.status=='Open'?[]:[{s:t.status,t:t.updated}]),assignee:0,resolvedAt:t.status=='Resolved'?t.updated:null,rating:null,notes:[],kw:1,aa:0}));s.log=mkLog(s.tickets,s.team);return s}}catch(e){}
return seed()}
let S=load(),view='dashboard',R=7,cur=null,cq='',kbq='',kbc='All',tt;
const F={d:{q:'',s:'All',p:'All',y:'All',n:8},t:{q:'',s:'All',p:'All',y:'All',sort:'new',n:10}},T=id=>S.tickets.find(t=>t.id==id),M=id=>S.team.find(m=>m.id==id);
function save(){try{localStorage.setItem(KEY,JSON.stringify(S))}catch(e){}}
function toast(m){const e=$('toast');e.textContent=m;e.classList.add('show');clearTimeout(tt);tt=setTimeout(()=>e.classList.remove('show'),2000)}
function log(k,t,text,sub){S.log.unshift({ts:Date.now(),k,id:t?t.id:0,text,sub:sub||''});S.log.length=Math.min(S.log.length,300)}
function runRules(f){const r=S.rules,now=Date.now(),act=t=>t.status!='Resolved',c={a:0,k:0,e:0};
S.tickets.forEach(t=>{
if(r.k&&(f=='k'||!t.kw)&&act(t)){t.kw=1;if(t.priority!='High'&&KW.test(t.desc)){t.priority='High';c.k++;log('auto',t,'Automation set priority to High','Keyword rule · '+t.type)}}
if(r.e&&!t.esc&&t.status=='Open'&&t.priority!='High'&&now-t.created>S.settings.sla*HR){t.esc=1;t.priority=t.priority=='Low'?'Medium':'High';c.e++;log('auto',t,'Automation raised priority to '+t.priority,'Open for over '+S.settings.sla+'h')}
if(r.a&&!t.assignee&&(f=='a'||!t.aa)&&act(t)&&S.team.length){t.aa=1;const m=S.team.map(m=>[m,S.tickets.filter(x=>x.assignee==m.id&&act(x)).length]).sort((a,b)=>a[1]-b[1])[0][0];t.assignee=m.id;c.a++;log('auto',t,'Automation assigned ticket to '+m.name,'Least-loaded agent')}});
for(const k in c)r.n[k]+=c[k];return c.a+c.k+c.e}
function commit(m){runRules();save();render();if(cur&&T(cur))openTicket(cur);if(m)toast(m)}
function setSt(id,s){const t=T(id);if(!t||t.status==s)return;const n=Date.now();t.status=s;t.updated=n;t.hist.push({s,t:n});if(s=='Resolved')t.resolvedAt=n;else{t.resolvedAt=null;t.rating=null}
log(s=='Resolved'?'res':'upd',t,S.settings.name+(s=='Resolved'?' resolved a ticket':' updated a ticket'),t.type+' · '+s);commit('Ticket #'+id+' moved to '+s)}
function setF(id,k,v){const t=T(id);if(!t)return;t[k]=v;t.updated=Date.now();if(k!='rating')log('upd',t,S.settings.name+' updated a ticket',k+' changed');commit('Ticket updated')}
function addN(id){const t=T(id),x=$('nt').value.trim();if(!t||!x)return;t.notes.push({x,t:Date.now()});t.updated=Date.now();log('note',t,S.settings.name+' added a note',t.type);commit('Note added')}
function del(id){if(!confirm('Delete ticket #'+id+'?'))return;S.tickets=S.tickets.filter(t=>t.id!=id);log('del',null,S.settings.name+' deleted ticket #'+id,'');if(cur==id)closeM();commit('Ticket deleted')}
function openM(h,s,b,f){$('mh').textContent=h;$('ms').innerHTML=s;$('mb').innerHTML=b;$('mf').innerHTML=f;cur=null;$('modalBg').classList.add('show')}
function closeM(){$('modalBg').classList.remove('show');cur=null}
function newT(p){p=p||{};openM('Create a new ticket','Capture the customer issue and start tracking it instantly.',
`<div class="field"><label>Customer name *</label><input id="fn" value="${esc(p.name)}" placeholder="e.g. Rahul Kumar"></div><div class="field"><label>Phone *</label><input id="fp" value="${esc(p.phone)}" maxlength="10" inputmode="numeric" placeholder="10-digit number" oninput="fillN(this.value)"></div>
<div class="field"><label>Issue type</label><select id="fy">${TY.map(x=>`<option>${x}</option>`).join('')}</select></div><div class="field"><label>Priority</label><select id="fq">${PR.map(x=>`<option${x=='Medium'?' selected':''}>${x}</option>`).join('')}</select></div>
<div class="field full"><label>Assign to</label><select id="fa"><option value="0">${S.rules.a?'Auto-assign (least busy agent)':'Unassigned'}</option>${S.team.map(m=>`<option value="${m.id}">${esc(m.name)}</option>`).join('')}</select></div>
<div class="field full"><label>Issue details *</label><textarea id="fd" placeholder="Describe the customer's problem"></textarea></div><div class="form-msg" id="fm"></div>`,
`<button class="btn secondary" onclick="closeM()">Cancel</button><button class="btn primary" onclick="addT()">Create ticket</button>`);setTimeout(()=>$(p.name?'fd':'fn').focus(),50)}
function fillN(v){if(v.length==10&&!$('fn').value.trim()){const t=S.tickets.find(x=>x.phone==v);if(t)$('fn').value=t.name}}
function addT(){const n=$('fn').value.trim(),p=$('fp').value.trim(),d=$('fd').value.trim(),e=m=>{$('fm').textContent=m};
if(!n||!p||!d)return e('Please fill customer name, phone and issue details.');if(!/^\d{10}$/.test(p))return e('Phone must be exactly 10 digits.');
const now=Date.now(),t={id:Math.max(10000,...S.tickets.map(x=>+x.id))+1,name:n,phone:p,desc:d,type:$('fy').value,priority:$('fq').value,status:'Open',created:now,updated:now,hist:[{s:'Open',t:now}],assignee:+$('fa').value,resolvedAt:null,rating:null,notes:[]};
if(t.assignee)t.aa=1;S.tickets.push(t);log('new',t,n+' sent a new ticket',t.type);closeM();commit('Ticket created successfully')}
function openTicket(id){const t=T(id);if(!t)return;const so=(a,v)=>a.map(x=>`<option${x==v?' selected':''}>${x}</option>`).join('');
openM('Ticket #'+id,esc(t.type)+' · created '+fmt(t.created),
`<div class="field"><label>Customer</label><b>${esc(t.name)}</b><br><small>${esc(t.phone)}</small></div><div class="field"><label>Timeline</label><div style="font-size:12px">Updated ${ago(t.updated)}<br>${t.resolvedAt?'Resolved in '+dur(t.resolvedAt-t.created):'Open for '+dur(Date.now()-t.created)}</div></div>
<div class="field full"><label>Issue</label><div style="font-size:13px;line-height:1.5">${esc(t.desc)}</div></div>
<div class="field"><label>Status</label><select onchange="setSt(${id},this.value)">${so(ST,t.status)}</select></div><div class="field"><label>Priority</label><select onchange="setF(${id},'priority',this.value)">${so(PR,t.priority)}</select></div>
<div class="field"><label>Assignee</label><select onchange="setF(${id},'assignee',+this.value)"><option value="0">Unassigned</option>${S.team.map(m=>`<option value="${m.id}"${m.id==t.assignee?' selected':''}>${esc(m.name)}</option>`).join('')}</select></div>
<div class="field"><label>Customer rating${t.status=='Resolved'?'':' (after resolving)'}</label><select ${t.status=='Resolved'?'':'disabled'} onchange="setF(${id},'rating',+this.value||null)"><option value="0">Not rated</option>${[5,4,3,2,1].map(r=>`<option value="${r}"${t.rating==r?' selected':''}>${r} – ${LBL[r-1]}</option>`).join('')}</select></div>
<div class="field full"><label>Notes</label>${t.notes.map(n=>`<div class="note">${esc(n.x)}<small>${fmt(n.t)}</small></div>`).join('')||'<div class="vs">No notes yet.</div>'}<textarea id="nt" style="min-height:60px;margin-top:8px" placeholder="Add an internal note..."></textarea></div>`,
`<button class="btn danger" onclick="del(${id})">Delete</button><button class="btn secondary" onclick="addN(${id})">Add note</button><button class="btn primary" onclick="closeM()">Done</button>`);cur=id}
/* ---- tables & filters ---- */
function fl(r){const f=F[r],q=f.q.toLowerCase(),o=f.sort||'new',a=S.tickets.filter(t=>(f.s=='All'||t.status==f.s)&&(f.p=='All'||t.priority==f.p)&&(f.y=='All'||t.type==f.y)&&(!q||[t.name,t.phone,t.desc,t.type,t.id].join(' ').toLowerCase().includes(q)));
return a.sort((x,y)=>o=='old'?x.created-y.created:o=='pri'?PR.indexOf(y.priority)-PR.indexOf(x.priority)||y.created-x.created:o=='sta'?ST.indexOf(x.status)-ST.indexOf(y.status)||y.created-x.created:y.created-x.created)}
function row(t){const m=M(t.assignee);return `<tr onclick="openTicket(${t.id})"><td><div class="ticket-id">#${t.id}</div><div class="subject">${esc(t.desc)}</div></td><td><div class="customer"><div class="miniav">${esc(ini(t.name))}</div><div><b>${esc(t.name)}</b><small>${esc(t.phone)}</small></div></div></td><td><select class="select-status pill ${sc(t.status)}" onclick="event.stopPropagation()" onchange="setSt(${t.id},this.value)">${ST.map(s=>`<option${s==t.status?' selected':''}>${s}</option>`).join('')}</select></td><td><span class="priority ${t.priority}">${icon({High:'up',Medium:'minus',Low:'down'}[t.priority],11,3)} ${t.priority}</span></td><td title="${fmt(t.created)}">${ago(t.created)}</td><td>${m?`<div class="miniav" title="${esc(m.name)}">${esc(ini(m.name))}</div>`:'<span class="vs">—</span>'}</td><td><button class="delete" onclick="event.stopPropagation();del(${t.id})">Delete</button></td></tr>`}
function tbl(r){const a=fl(r),n=F[r].n;if(!a.length)return EM;return `<table class="ticket-table"><thead><tr><th>Ticket</th><th>Customer</th><th>Status</th><th>Priority</th><th>Created</th><th>Assignee</th><th></th></tr></thead><tbody>${a.slice(0,n).map(row).join('')}</tbody></table><div class="vs" style="padding:10px 4px">Showing ${Math.min(n,a.length)} of ${a.length} tickets ${a.length>n?`<button class="link" onclick="F.${r}.n+=10;$('tb-${r}').innerHTML=tbl('${r}')">Show more</button>`:''}</div>`}
function bar(r){const f=F[r],o=(a,v,l)=>`<option value="All"${v=='All'?' selected':''}>${l}</option>`+a.map(x=>`<option${x==v?' selected':''}>${x}</option>`).join(''),h=k=>`onchange="fset('${r}','${k}',this.value)"`;
return `<div class="filters${r=='t'?' f5':''}"><div class="search-small"><input value="${esc(f.q)}" placeholder="Search by name, phone, ID or issue..." oninput="fset('${r}','q',this.value)"></div><select ${h('s')}>${o(ST,f.s,'All Statuses')}</select><select ${h('p')}>${o(PR,f.p,'All Priorities')}</select><select ${h('y')}>${o(TY,f.y,'All Types')}</select>${r=='t'?`<select ${h('sort')}>${[['new','Newest first'],['old','Oldest first'],['pri','Highest priority'],['sta','By status']].map(x=>`<option value="${x[0]}"${f.sort==x[0]?' selected':''}>${x[1]}</option>`).join('')}</select>`:''}</div>`}
function fset(r,k,v){F[r][k]=v;F[r].n=r=='t'?10:8;$('tb-'+r).innerHTML=tbl(r)}
function gs(v){F.t.q=v;F.t.n=10;if(view!='tickets'){if(v)go('tickets')}else{const i=document.querySelector('#page .search-small input');if(i)i.value=v;$('tb-t').innerHTML=tbl('t')}}
/* ---- charts ---- */
function dl(c,p,g){const d=p?Math.round((c-p)/p*100):(c?null:0);return `<div class="delta ${d==0?'flat':(d===null||d>0)==g?'up':'down'}">${d===null?'↑ new':d>0?'↑ '+d+'%':d<0?'↓ '+-d+'%':'– 0%'}</div>`}
function spark(v,col){const mx=Math.max(...v),mn=Math.min(...v),n=v.length-1||1,l=v.map((y,i)=>(2+i*106/n).toFixed(1)+' '+(mx==mn?22:40-(y-mn)/(mx-mn)*34).toFixed(1)).join(' L');return `<svg class="spark" viewBox="0 0 110 45"><path d="M${l}" fill="none" stroke="${col}" stroke-width="2"/><path d="M${l} V45 H2 Z" fill="${col}1a"/></svg>`}
const KP=[['total','Total Tickets','ticket',()=>true,'#1769ff',1],['open','Open','alert',s=>s=='Open','#ff5261',0],['progress','In Progress','clock',s=>s=='In Progress','#f6ae1a',1],['resolved','Resolved','check',s=>s=='Resolved','#19b977',1]];
function kpi(k){const[c,l,ic,f,col,g]=k,n=Date.now(),cu=snap(n,f),pv=snap(n-R*DAY,f),v=[];for(let i=R-1;i>=0;i--)v.push(snap(Math.min(dayS(i-1),n),f));
return `<article class="kpi ${c}"><div class="kpi-top"><div class="kico">${icon(ic,18)}</div><span>${l}</span></div><div class="kpi-mid"><div><div class="kpi-num">${cu}</div>${dl(cu,pv,g)}<div class="vs">vs. ${R} days ago</div></div>${spark(v,col)}</div></article>`}
const kc=(l,ic,c,v,d)=>`<article class="kpi ${c}"><div class="kpi-top"><div class="kico">${icon(ic,18)}</div><span>${l}</span></div><div class="kpi-mid"><div><div class="kpi-num">${v}</div>${d}<div class="vs">vs. previous ${R} days</div></div></div></article>`;
const lab=i=>new Date(dayS(i)).toLocaleDateString('en-US',R<=7?{weekday:'short'}:{day:'numeric',month:'short'}),
rsel=full=>`<select class="date-btn" onchange="R=+this.value;render()">${[7,14,30].map(n=>`<option value="${n}"${n==R?' selected':''}>Last ${n} days${full?' · '+fmtD(dayS(n-1))+' – '+fmtD(Date.now()):''}</option>`).join('')}</select>`;
function bars(){const d=[];for(let i=R-1;i>=0;i--){const T2=Math.min(dayS(i-1),Date.now());d.push([i,ST.map(s=>snap(T2,x=>x==s))])}
const mx=Math.max(1,...d.map(x=>x[1][0]+x[1][1]+x[1][2])),k=Math.ceil(R/7);
return d.map(([i,c],j)=>`<div class="barcol" title="${lab(i)}: Open ${c[0]}, In Progress ${c[1]}, Resolved ${c[2]}"><div class="stack" style="width:70%;max-width:24px">${c.map((n,q)=>`<div class="seg ${'rag'[q]}" style="height:${n/mx*110}px"></div>`).join('')}</div><div class="xlab">${j%k==0?lab(i):''}</div></div>`).join('')}
function vol(){const v=[],W=760,H=190,L=30,Rr=16,Tp=14,Bt=30;for(let i=R-1;i>=0;i--)v.push(S.tickets.filter(t=>t.created>=dayS(i)&&t.created<dayS(i-1)).length);
const mx=Math.max(4,Math.ceil(Math.max(...v)/4)*4),X=i=>L+i*(W-L-Rr)/(R-1),Y=x=>H-Bt-x/mx*(H-Bt-Tp),k=Math.ceil(R/7),p=v.map((y,i)=>X(i)+','+Y(y)).join(' ');
return `<svg viewBox="0 0 ${W} ${H}"><defs><linearGradient id="fl" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#1769ff" stop-opacity=".18"/><stop offset="1" stop-color="#1769ff" stop-opacity="0"/></linearGradient></defs>${[0,1,2,3,4].map(q=>`<line x1="${L}" x2="${W-Rr}" y1="${Y(mx/4*q)}" y2="${Y(mx/4*q)}" stroke="#edf1f6"/><text x="2" y="${Y(mx/4*q)+4}" font-size="10" fill="#8f99aa">${mx/4*q}</text>`).join('')}<polygon points="${X(0)},${Y(0)} ${p} ${X(R-1)},${Y(0)}" fill="url(#fl)"/><polyline points="${p}" fill="none" stroke="#1769ff" stroke-width="2.5"/>${v.map((y,i)=>`<circle cx="${X(i)}" cy="${Y(y)}" r="3.5" fill="#1769ff" stroke="#fff" stroke-width="2"><title>${lab(R-1-i)}: ${y} ticket${y==1?'':'s'}</title></circle>${i%k==0?`<text x="${X(i)}" y="${H-10}" font-size="10" fill="#8f99aa" text-anchor="middle">${lab(R-1-i)}</text>`:''}`).join('')}</svg>`}
function pcts(v){const t=v.reduce((a,b)=>a+b,0);if(!t)return v.map(()=>0);const r=v.map(x=>x/t*100),f=r.map(Math.floor);let k=100-f.reduce((a,b)=>a+b,0);r.map((x,i)=>[x-f[i],i]).sort((a,b)=>b[0]-a[0]).slice(0,k).forEach(a=>f[a[1]]++);return f}
function pie(it,mid,sub){const v=it.map(i=>i.v),t=v.reduce((a,b)=>a+b,0),p=pcts(v);let a=0;const g=t?it.map(i=>{const s=a;a+=i.v/t*100;return i.c+' '+s+'% '+a+'%'}).join(','):'#e6edf6 0% 100%';
return `<div class="csat-body"><div class="donut" style="background:conic-gradient(${g})"><div class="donut-copy">${mid}<small>${sub}</small></div></div><div class="legend-list">${it.map((i,j)=>`<div class="lg"><i class="dotc" style="background:${i.c}"></i><span>${esc(i.l)}</span><b>${i.v} · ${p[j]}%</b></div>`).join('')||'<div class="vs">No data yet</div>'}</div></div>`}
function csat(){const a=dayS(R-1),rz=S.tickets.filter(t=>t.resolvedAt>=a),rt=rz.filter(t=>t.rating),it=[4,3,2,1,0].map(i=>({l:LBL[i],v:rt.filter(t=>t.rating==i+1).length,c:COL[i]})),p=pcts(it.map(i=>i.v));
return `<div class="panel-h"><div><h2>Customer Satisfaction</h2><p>${rt.length} rated of ${rz.length} tickets resolved in the last ${R} days.</p></div>${rsel()}</div>`+pie(it,rt.length?(p[0]+p[1])+'%':'–','Satisfaction Rate')}
const AI={new:['#eaf2ff','#1769ff','plus'],res:['#e6f8f0','#11a365','check'],upd:['#fff5df','#d78b00','refresh'],note:['#fff5df','#d78b00','edit'],auto:['#f1eaff','#7c3aed','zap'],del:['#fff0f2','#e83a4e','trash']};
const ai=l=>{const c=AI[l.k]||AI.upd;return `<div class="activity-item"><div class="act-icon" style="background:${c[0]};color:${c[1]}">${icon(c[2],14)}</div><div class="act-text"><b>${esc(l.text)}</b><div>${T(l.id)?`<a onclick="openTicket(${l.id})">#${l.id}</a> — `:''}${esc(l.sub)}</div></div><div class="ago">${ago(l.ts)}</div></div>`};
const acts=(n)=>S.log.slice(0,n).map(ai).join('')||'<div class="empty">No recent activity.</div>';
function allAct(){openM('All activity','Latest '+Math.min(50,S.log.length)+' events','<div class="field full">'+acts(50)+'</div>','<button class="btn primary" onclick="closeM()">Close</button>')}
/* ---- views ---- */
function dash(){const h=new Date().getHours(),n=S.tickets.filter(t=>t.created>=dayS(R-1)).length;
return `<div class="headrow"><div><h1>${h<12?'Good morning':h<17?'Good afternoon':'Good evening'}, ${esc(String(S.settings.name).split(/\s+/)[0])}</h1><p>Here's what's happening with your support team today.</p></div>${rsel(1)}</div><section class="kpis">${KP.map(kpi).join('')}</section>
<section class="grid-main"><div class="panel"><div class="panel-h"><div><h2>Recent Tickets</h2><p>The latest customer support tickets. Click a row for details.</p></div><span><button class="link" onclick="newT()">+ New ticket</button> <button class="link" onclick="go('tickets')">View all →</button></span></div>${bar('d')}<div class="ticket-wrap" id="tb-d">${tbl('d')}</div></div>
<div class="rightcol"><div class="panel"><div class="panel-h"><div><h2>Ticket Trends</h2><p>Ticket status at the end of each day.</p></div>${rsel()}</div><div class="chart-legend"><span><i class="dotc" style="background:#ff7b82"></i>Open</span><span><i class="dotc" style="background:#ffc44f"></i>In Progress</span><span><i class="dotc" style="background:#4cc38a"></i>Resolved</span></div><div class="trend-chart"><div class="bars">${bars()}</div></div></div>
<div class="panel"><div class="panel-h"><div><h2>Recent Activity</h2></div><button class="link" onclick="allAct()">View all →</button></div><div class="activity">${acts(5)}</div></div></div></section>
<section class="bottom"><div class="panel line-card"><div class="panel-h"><div><h2>Ticket Volume</h2><p>${n} tickets received in the last ${R} days.</p></div>${rsel()}</div><div class="line-wrap">${vol()}</div></div><div class="panel csat">${csat()}</div></section>`}
function tks(){return `<div class="headrow"><div><h1>Tickets</h1><p>Search, filter, update and manage every support ticket.</p></div><span><button class="btn secondary" onclick="csv()">Export CSV</button><button class="btn primary" onclick="newT()">+ New ticket</button></span></div><div class="panel"><div class="panel-h"><div><h2>All Tickets</h2><p>Click a row to open details, notes and customer rating.</p></div></div>${bar('t')}<div class="ticket-wrap" id="tb-t">${tbl('t')}</div></div>`}
function custs(){const m={};S.tickets.slice().sort((a,b)=>a.created-b.created).forEach(t=>{const c=m[t.phone]||(m[t.phone]={phone:t.phone,n:0,o:0,r:0,last:0,rs:[]});c.name=t.name;c.n++;t.status=='Resolved'?c.r++:c.o++;c.last=Math.max(c.last,t.created);if(t.rating)c.rs.push(t.rating)});return Object.values(m)}
function ctb(){const q=cq.toLowerCase(),a=custs().filter(c=>!q||(c.name+c.phone).toLowerCase().includes(q)).sort((x,y)=>y.last-x.last);if(!a.length)return '<div class="empty">No customers found.</div>';
return `<table class="ticket-table"><thead><tr><th>Customer</th><th>Tickets</th><th>Active</th><th>Resolved</th><th>Avg rating</th><th>Last ticket</th></tr></thead><tbody>${a.map(c=>`<tr onclick="openCust('${esc(c.phone)}')"><td><div class="customer"><div class="miniav">${esc(ini(c.name))}</div><div><b>${esc(c.name)}</b><small>${esc(c.phone)}</small></div></div></td><td>${c.n}</td><td>${c.o}</td><td>${c.r}</td><td>${c.rs.length?avg(c.rs).toFixed(1)+' ★':'—'}</td><td>${ago(c.last)}</td></tr>`).join('')}</tbody></table>`}
function cus(){return `<div class="headrow"><div><h1>Customers</h1><p>${custs().length} customers, built automatically from ticket history.</p></div><button class="btn primary" onclick="newT()">+ New ticket</button></div><div class="panel"><div class="panel-h"><div><h2>All Customers</h2><p>Click a customer to see their tickets.</p></div></div><div class="filters" style="grid-template-columns:1fr"><div class="search-small"><input value="${esc(cq)}" placeholder="Search by name or phone..." oninput="cq=this.value;$('tb-c').innerHTML=ctb()"></div></div><div class="ticket-wrap" id="tb-c">${ctb()}</div></div>`}
function openCust(p){const c=custs().find(x=>x.phone==p);if(!c)return;openM(c.name,esc(p)+' · '+c.n+' tickets, '+c.o+' active','<div class="field full">'+S.tickets.filter(t=>t.phone==p).sort((x,y)=>y.created-x.created).map(t=>`<div class="note" style="cursor:pointer;display:flex;justify-content:space-between;gap:8px" onclick="openTicket(${t.id})"><span><b>#${t.id}</b> ${esc(t.type)}<small>${esc(t.desc.slice(0,80))}</small></span><span class="pill ${sc(t.status)}" style="height:fit-content">${t.status}</span></div>`).join('')+'</div>',`<button class="btn secondary" onclick="closeM()">Close</button><button class="btn primary" onclick="newC('${esc(p)}')">+ New ticket</button>`)}
function newC(p){const c=custs().find(x=>x.phone==p);newT({name:c.name,phone:p})}
function ana(){const a=dayS(R-1),b=dayS(2*R-1),cr=S.tickets.filter(t=>t.created>=a),pc=S.tickets.filter(t=>t.created>=b&&t.created<a),rz=S.tickets.filter(t=>t.resolvedAt>=a),pz=S.tickets.filter(t=>t.resolvedAt>=b&&t.resolvedAt<a),
av=x=>avg(x.map(t=>t.resolvedAt-t.created)),rr=x=>x.length?Math.round(x.filter(t=>t.status=='Resolved').length/x.length*100):0,
P=(h,it)=>`<div class="panel"><div class="panel-h"><div><h2>${h}</h2><p>${cr.length} tickets created in the last ${R} days</p></div></div>${pie(it.filter(i=>i.v),cr.length,'Tickets')}</div>`;
return `<div class="headrow"><div><h1>Analytics</h1><p>Every number is calculated live from your tickets.</p></div>${rsel(1)}</div><section class="kpis">${kc('Tickets Created','ticket','total',cr.length,dl(cr.length,pc.length,1))}${kc('Tickets Resolved','check','resolved',rz.length,dl(rz.length,pz.length,1))}${kc('Avg Resolution Time','clock','progress',rz.length?dur(av(rz)):'—',dl(rz.length?av(rz):0,pz.length?av(pz):0,0))}${kc('Resolution Rate','chart','total',rr(cr)+'%',dl(rr(cr),rr(pc),1))}</section>
<div class="row2" style="margin-top:0">${P('By Status',ST.map((s,i)=>({l:s,v:cr.filter(t=>t.status==s).length,c:['#ff7b82','#ffc44f','#4cc38a'][i]})))}${P('By Priority',PR.map((s,i)=>({l:s,v:cr.filter(t=>t.priority==s).length,c:['#2b78ed','#f6ae1a','#ff5261'][i]})))}</div>
<div class="row2">${P('By Issue Type',TY.map((y,i)=>({l:y,v:cr.filter(t=>t.type==y).length,c:PAL[i]})))}${P('By Assignee',[{l:'Unassigned',v:cr.filter(t=>!M(t.assignee)).length,c:'#94a3b8'}].concat(S.team.map((m,i)=>({l:m.name,v:cr.filter(t=>t.assignee==m.id).length,c:PAL[i]}))))}</div>
<div class="panel line-card" style="margin-top:16px"><div class="panel-h"><div><h2>Ticket Volume</h2><p>Tickets created per day.</p></div></div><div class="line-wrap">${vol()}</div></div><div class="panel csat" style="margin-top:16px">${csat()}</div>`}
function kbCards(){const q=kbq.toLowerCase(),a=S.kb.filter(x=>(kbc=='All'||x.cat==kbc)&&(!q||(x.title+' '+x.body).toLowerCase().includes(q)));
return a.length?`<div class="card-grid">${a.map(x=>`<div class="card"><span class="priority Low">${esc(x.cat)}</span><h4 style="margin-top:8px">${esc(x.title)}</h4><p>${esc(x.body.slice(0,110))}${x.body.length>110?'…':''}</p><div class="vs">${x.views} views · ${icon('thumb',12)} ${x.up}</div><div style="display:flex;gap:8px;margin-top:10px"><button class="btn primary sm" onclick="openKb(${x.id})">Read</button><button class="btn danger sm" onclick="delKb(${x.id})">Delete</button></div></div>`).join('')}</div>`:'<div class="empty">No articles found.</div>'}
function kbv(){return `<div class="headrow"><div><h1>Knowledge Base</h1><p>Help articles your team can follow when answering customers.</p></div><button class="btn primary" onclick="newKb()">+ New article</button></div><div class="panel"><div class="filters" style="grid-template-columns:2fr 1fr;padding-top:14px"><div class="search-small"><input value="${esc(kbq)}" placeholder="Search articles..." oninput="kbq=this.value;$('tb-k').innerHTML=kbCards()"></div><select onchange="kbc=this.value;$('tb-k').innerHTML=kbCards()"><option value="All">All Categories</option>${CATS.map(c=>`<option${c==kbc?' selected':''}>${c}</option>`).join('')}</select></div><div id="tb-k">${kbCards()}</div></div>`}
function openKb(id,nv){const x=S.kb.find(k=>k.id==id);if(!x)return;if(!nv){x.views++;save()}openM(x.title,esc(x.cat),`<div class="field full" style="font-size:13px;line-height:1.7">${esc(x.body).replace(/\n/g,'<br>')}</div>`,`<button class="btn secondary" onclick="kbUp(${id})">${icon('thumb',14)} Helpful (${x.up})</button><button class="btn primary" onclick="closeM()">Close</button>`)}
function kbUp(id){S.kb.find(k=>k.id==id).up++;save();render();openKb(id,1)}
function delKb(id){if(!confirm('Delete this article?'))return;S.kb=S.kb.filter(k=>k.id!=id);save();render();toast('Article deleted')}
function newKb(){openM('New article','Add a how-to for your team.',`<div class="field"><label>Title *</label><input id="kt"></div><div class="field"><label>Category</label><select id="kc">${CATS.map(c=>`<option>${c}</option>`).join('')}</select></div><div class="field full"><label>Content *</label><textarea id="kx" style="min-height:140px"></textarea></div><div class="form-msg" id="fm"></div>`,`<button class="btn secondary" onclick="closeM()">Cancel</button><button class="btn primary" onclick="addKb()">Publish</button>`)}
function addKb(){const t=$('kt').value.trim(),b=$('kx').value.trim();if(t.length<3||b.length<10)return $('fm').textContent='Add a title and at least a sentence of content.';S.kb.unshift({id:Math.max(0,...S.kb.map(k=>k.id))+1,title:t,cat:$('kc').value,body:b,views:0,up:0});save();closeM();render();toast('Article published')}
function aut(){const r=S.rules,D=[['a','Auto-assign new tickets','Gives every new unassigned ticket to the agent with the fewest active tickets.'],['k','Priority keywords','Sets priority to High when the ticket text contains: urgent, immediate, asap, crash, fraud, refund, not working or failed.'],['e','SLA escalation',`Raises priority (once per ticket) when a ticket is still Open after ${S.settings.sla} hours. Change the limit in Settings.`]],l=S.log.filter(x=>x.k=='auto').slice(0,8);
return `<div class="headrow"><div><h1>Automation</h1><p>Rules run automatically when tickets are created and every minute.</p></div></div><div class="panel"><div class="panel-h"><div><h2>Rules</h2></div></div><div class="card-grid">${D.map(d=>`<div class="card"><div style="display:flex;justify-content:space-between;align-items:center"><h4>${d[1]}</h4><span class="tog"><input type="checkbox" ${r[d[0]]?'checked':''} onchange="S.rules['${d[0]}']=this.checked?1:0;commit(this.checked?'Rule enabled':'Rule disabled')"><i></i></span></div><p>${d[2]}</p><div class="vs">Triggered ${r.n[d[0]]} time${r.n[d[0]]==1?'':'s'}</div><button class="btn secondary sm" style="margin-top:10px" onclick="rn('${d[0]}')">Run now</button></div>`).join('')}</div></div><div class="panel" style="margin-top:16px"><div class="panel-h"><div><h2>Automation log</h2></div></div><div class="activity">${l.map(ai).join('')||'<div class="empty">No automation events yet.</div>'}</div></div>`}
function rn(k){if(!S.rules[k])return toast('Turn the rule on first');const n=runRules(k);save();render();toast(n?'Rule applied to '+n+' ticket'+(n==1?'':'s'):'Nothing to apply right now')}
function tm(){const un=S.tickets.filter(t=>!M(t.assignee)&&t.status!='Resolved').length;
return `<div class="headrow"><div><h1>Team</h1><p>${S.team.length} agents · ${un} active tickets unassigned.</p></div></div><div class="panel" style="margin-bottom:16px"><div class="panel-h"><div><h2>Add team member</h2></div></div><div class="filters" style="grid-template-columns:2fr 1fr auto"><input id="tn" placeholder="Full name"><select id="tr"><option>Agent</option><option>Senior Agent</option><option>Support Lead</option></select><button class="btn primary" onclick="addM()">Add member</button></div><div class="form-msg" id="fm" style="padding:0 17px 10px"></div></div>
<div class="card-grid" style="padding:0">${S.team.map(m=>{const a=S.tickets.filter(t=>t.assignee==m.id),rz=a.filter(t=>t.resolvedAt),rt=a.filter(t=>t.rating);return `<div class="card"><div class="customer" style="margin-bottom:10px"><div class="miniav" style="width:40px;height:40px;font-size:12px">${esc(ini(m.name))}</div><div><b style="font-size:14px">${esc(m.name)}</b><small style="font-size:11px">${esc(m.role)}</small></div></div><div class="kv"><span>Active tickets</span><b>${a.length-rz.length}</b></div><div class="kv"><span>Resolved</span><b>${rz.length}</b></div><div class="kv"><span>Avg resolution time</span><b>${rz.length?dur(avg(rz.map(t=>t.resolvedAt-t.created))):'—'}</b></div><div class="kv"><span>Avg rating</span><b>${rt.length?avg(rt.map(t=>t.rating)).toFixed(1)+' / 5':'—'}</b></div><button class="btn danger sm" style="margin-top:10px" onclick="delM(${m.id})">Remove</button></div>`}).join('')}</div>`}
function addM(){const n=$('tn').value.trim();if(n.length<2)return $('fm').textContent='Enter the team member\'s name.';S.team.push({id:Math.max(0,...S.team.map(m=>m.id))+1,name:n,role:$('tr').value});commit('Team member added')}
function delM(id){if(!confirm('Remove this member? Their tickets become unassigned.'))return;S.tickets.forEach(t=>{if(t.assignee==id)t.assignee=0});S.team=S.team.filter(m=>m.id!=id);commit('Member removed')}
function stg(){const s=S.settings;return `<div class="headrow"><div><h1>Settings</h1><p>Profile, service-level rules and your data.</p></div></div><div class="row2" style="margin-top:0"><div class="panel"><div class="panel-h"><div><h2>Profile & rules</h2></div></div><div class="form"><div class="field"><label>Your name</label><input id="sn" value="${esc(s.name)}"></div><div class="field"><label>Role</label><input id="sr" value="${esc(s.role)}"></div><div class="field"><label>Escalate Open tickets after (hours)</label><input id="ss" type="number" min="1" max="720" value="${s.sla}"></div><div class="field"><label>Notifications</label><div style="display:flex;gap:10px;align-items:center;font-size:13px"><span class="tog"><input type="checkbox" id="sm" ${s.notif?'checked':''}><i></i></span>High-priority alerts</div></div><div class="form-msg" id="fm"></div></div><div class="modal-foot"><button class="btn primary" onclick="saveS()">Save settings</button></div></div>
<div class="panel"><div class="panel-h"><div><h2>Data</h2><p>Everything is stored in this browser only.</p></div></div><div class="form" style="grid-template-columns:1fr"><button class="btn secondary" onclick="csv()">Export tickets (CSV)</button><button class="btn secondary" onclick="dld('supporthub-backup.json',JSON.stringify(S,null,1),'application/json')">Download full backup (JSON)</button><button class="btn secondary" onclick="rst()">Reset to demo data</button><button class="btn danger" onclick="clr()">Delete all tickets</button></div></div></div>`}
function saveS(){const h=Math.round(+$('ss').value);if(!(h>=1&&h<=720))return $('fm').textContent='Enter hours between 1 and 720.';S.settings={name:$('sn').value.trim()||'Support Admin',role:$('sr').value.trim()||'Support Team',sla:h,notif:$('sm').checked};commit('Settings saved')}
function rst(){if(confirm('Replace all data with fresh demo data?')){S=seed();save();render();toast('Demo data restored')}}
function clr(){if(confirm('Delete every ticket? This cannot be undone.')){S.tickets=[];S.log=[];commit('All tickets deleted')}}
function dld(n,x,m){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([x],{type:m}));a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),999)}
function csv(){const q=v=>'"'+String(v??'').replace(/^[=+\-@]/,"'$&").replace(/"/g,'""')+'"',iso=t=>t?new Date(t).toISOString():'';dld('tickets.csv',[['ID','Customer','Phone','Type','Priority','Status','Assignee','Created','Resolved','Rating','Details'].map(q).join(',')].concat(S.tickets.map(t=>[t.id,t.name,t.phone,t.type,t.priority,t.status,(M(t.assignee)||{}).name||'',iso(t.created),iso(t.resolvedAt),t.rating||'',t.desc].map(q).join(','))).join('\n'),'text/csv')}
/* ---- shell ---- */
const V={dashboard:dash,tickets:tks,customers:cus,analytics:ana,kb:kbv,automation:aut,team:tm,settings:stg};
function go(v){view=v;render();scrollTo(0,0)}
function tnp(){$('np').classList.toggle('show')}
function notif(){const a=S.tickets.filter(t=>t.status!='Resolved'&&t.priority=='High').sort((x,y)=>y.created-x.created),on=S.settings.notif;$('nd').style.display=on&&a.length?'block':'none';
$('np').innerHTML=`<div class="panel-h"><div><h2 style="font-size:15px">Notifications</h2><p>${on?a.length+' high-priority ticket'+(a.length==1?'':'s')+' need attention':'Turned off in Settings'}</p></div></div>`+(on?a.slice(0,8).map(t=>`<div class="ni" onclick="tnp();openTicket(${t.id})"><b>#${t.id} ${esc(t.name)}</b><small>${t.status} · ${esc(t.type)} · ${ago(t.created)}</small></div>`).join(''):'')}
function render(){$('nav').innerHTML=NAV.map(n=>`<button class="${n[0]==view?'active':''}" onclick="go('${n[0]}')"><span class="nav-ico">${icon(n[1],20)}</span><span class="txt">${n[2]}</span>${n[0]=='tickets'?`<span class="count">${S.tickets.length}</span>`:''}</button>`).join('');
$('page').innerHTML=V[view]();$('av').textContent=ini(S.settings.name);$('pn').textContent=S.settings.name;$('pr').textContent=S.settings.role;notif()}
document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()=='k'){e.preventDefault();$('gs').focus()}if(e.key=='Escape'){closeM();$('np').classList.remove('show')}});
document.addEventListener('click',e=>{if(!e.target.closest('#np,#bell'))$('np').classList.remove('show')});
runRules();save();render();
setInterval(()=>{if(runRules())save();const a=document.activeElement;if(!$('modalBg').classList.contains('show')&&!(a&&/INPUT|TEXTAREA|SELECT/.test(a.tagName)))render()},6e4);

/* ---- landing, auth, session ---- */
const USER_KEY='supporthub.user.v2';let user=null;
const LI={zap:'<path d="M13 2L3 14h9l-1 8 10-12h-9l1-8z"/>',users:'<path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M23 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75"/>',team:'<path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M23 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75"/>',chart:'<path d="M18 20V10M12 20V4M6 20v-6"/>',trend:'<path d="M3 17l6-6 4 4 8-8"/><path d="M14 7h7v7"/>',shield:'<path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/><path d="M9 12l2 2 4-4"/>',building:'<path d="M3 21h18M5 21V7l7-4 7 4v14"/><path d="M9 21v-6h6v6M9 10h.01M15 10h.01"/>',clock:'<circle cx="12" cy="12" r="10"/><path d="M12 6v6l4 2"/>',star:'<path d="M12 2l3.1 6.3 6.9 1-5 4.9 1.2 6.8L12 17.8 5.8 21l1.2-6.8-5-4.9 6.9-1z"/>',ticket:'<path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"/>',bell:'<path d="M18 8a6 6 0 0 0-12 0c0 7-3 9-3 9h18s-3-2-3-9"/><path d="M13.7 21a2 2 0 0 1-3.4 0"/>',cal:'<rect x="3" y="4" width="18" height="18" rx="2"/><path d="M16 2v4M8 2v4M3 10h18"/>',play:'<path d="M6 4l14 8-14 8z"/>',logout:'<path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"/><path d="M16 17l5-5-5-5M21 12H9"/>'};
function hydrate(){document.querySelectorAll('[data-ic]').forEach(e=>{if(LI[e.dataset.ic])e.innerHTML='<svg viewBox="0 0 24 24">'+LI[e.dataset.ic]+'</svg>'})}
function loadUser(){try{const u=JSON.parse(localStorage.getItem(USER_KEY));if(u&&u.name)user=u}catch(e){user=null}}
function showLanding(){$('landingRoot').classList.remove('hidden');['appRoot','np','fab'].forEach(i=>$(i).classList.add('hidden'));scrollTo(0,0)}
function showApp(){$('landingRoot').classList.add('hidden');['appRoot','np','fab'].forEach(i=>$(i).classList.remove('hidden'));closeAuth();render();scrollTo(0,0)}
function openAuth(){if(user){$('authName').value=user.name;$('authRole').value=user.role;$('authTeam').value=user.team}$('authBg').classList.add('show');setTimeout(()=>$('authName').focus(),40)}
function closeAuth(){$('authBg').classList.remove('show')}
function signIn(){const name=$('authName').value.trim();if(!name){toast('Please enter your name');$('authName').focus();return}
user={name,role:$('authRole').value,team:$('authTeam').value};try{localStorage.setItem(USER_KEY,JSON.stringify(user))}catch(e){}
S.settings.name=name;S.settings.role=user.role;save();showApp();
$('welcomeName').textContent=name.split(/\s+/)[0];$('welcomeText').textContent=user.role+' · '+user.team+' workspace is ready.';
$('welcomePopup').classList.add('show');setTimeout(()=>$('welcomePopup').classList.remove('show'),1600)}
function logout(){if(!confirm('Log out of SupportHub? Your ticket data stays saved in this browser.'))return;
try{localStorage.removeItem(USER_KEY)}catch(e){}user=null;$('authName').value='';showLanding();toast('Logged out')}
document.querySelectorAll('[data-auth-open]').forEach(b=>b.addEventListener('click',openAuth));
document.querySelectorAll('[data-lp-target]').forEach(b=>b.addEventListener('click',()=>{const e=$(b.dataset.lpTarget);if(e)e.scrollIntoView({behavior:'smooth',block:'start'})}));
$('lpWatchDemo').addEventListener('click',()=>$('lpPreview').scrollIntoView({behavior:'smooth',block:'center'}));
$('authClose').addEventListener('click',closeAuth);$('authEnter').addEventListener('click',signIn);
$('authBg').addEventListener('click',e=>{if(e.target===$('authBg'))closeAuth()});
$('authName').addEventListener('keydown',e=>{if(e.key==='Enter')signIn()});
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeAuth()});
hydrate();loadUser();if(user&&S.settings.name==='Support Admin'){S.settings.name=user.name;S.settings.role=user.role;save()}user?showApp():showLanding();
